name: 'Unit Test'
description: 'Run unit tests'
runs:
  using: "composite"
  steps:

    - name: Install dependencies
      shell: bash
      working-directory: vite-react-app
      run: npm ci
    - name: Run test
      shell: bash
      working-directory: vite-react-app
      run: npm run test
