name: 'Lint'
description: 'Run eslint'
runs:
  using: "composite"
  defaults:
    run: 
      working-directory: /vite-react-app
      shell: bash
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm install
    - name: Run lint
      run: npm run lint
