name: Continuous Integration

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Run npm lint action
      uses: ./.github/actions/lint

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run npm build action
      uses: ./.github/actions/build

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Run npm test action
      uses: ./.github/actions/test
