name: Continuous Integration

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run npm lint action
      uses: ./.github/actions/lint-action.yml
