name: Continuous Delivery

on:
  push:
    branches:
      - 'main'

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
    - name: Run npm build action
      uses: ./.github/actions/build
    - name: Create Branch
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        push_options: '--force'
        skip_checkout: true